---
- hosts: all
  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted
    become: yes
  
  tasks:
      - name: "Set Authorized Key"
        ansible.posix.authorized_key:
            user: root
            state: present
            key: "{{ lookup('file', '/home/pedro/.ssh/id_rsa.pub') }}"
        become: yes


      - name: "Instalando dependências e arquivos."
        apt:
            name:
                  - apache2
                  - php8.1
                  - python3
                  - libapache2-mod-php8.1
                  - php-ssh2
                  - php8.1-gd
                  - php8.1-mysql
                  - php8.1-ssh2
                  - python3-mysqldb
                  - php8.1-ssh2
                  - mysql-server
            state: latest
        become: yes

      - name: "Criar o banco de dados"
        mysql_db:
            name: wordpress_db
            state: present
            login_unix_socket: /run/mysqld/mysqld.sock
        become: yes

      - name: "Configurando o banco internamente"
        mysql_user:
            login_user: root
            name: wordpress_user
            password: Pedrao@123
            priv: 'wordpress_db.*:ALL'
            state: present

      - name: "Baixando a Versão mais recente do WordPress"
        get_url:
            url: 'https://wordpress.org/latest.tar.gz'
            dest: '/tmp/wordpress.tar.gz'

      - name: "Descompactando o Arquivo"
        unarchive:
            src: /tmp/wordpress.tar.gz
            dest: /var/www/
            remote_src: yes
        become: yes

      - name:
        copy:
            src: '/var/www/wordpress/wp-config-sample.php'
            dest: '/var/www/wordpress/wp-config.php'
            remote_src: yes
        become: yes 

      - name: "Configura o wp-config com as entradas do DB"
        replace:
            path: '/var/www/wordpress/wp-config.php'
            regexp: "{{ item.regex }}"
            replace: "{{ item.value }}"
        with_items:
            - { regex: 'database_name_here', value: 'wordpress_db'}
            - { regex: 'username_here', value: 'wordpress_user'}
            - { regex: 'password_here', value: 'Pedrao@123'}
        become: yes

      - name: "Configura Apache para servir o WordPress"
        copy:
            src: '/configs/000-default.conf'
            dest: '/etc/apache2/sites-available/000-default.conf'
            remote_src: yes
        notify:
            - restart apache
        become: yes

        
 


        
        

    

            

          
        
        
